# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ok.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import re
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

banner = '''                                            
 _   _  _   _  _      _   _  _____  _____   ___   _   _ 
| | | || | | || |    | \ | |/  ___|/  __ \ / _ \ | \ | |
| | | || | | || |    |  \| |\ `--. | /  \// /_\ \|  \| |
| | | || | | || |    | . ` | `--. \| |    |  _  || . ` |
\ \_/ /| |_| || |____| |\  |/\__/ /| \__/\| | | || |\  |
 \___/  \___/ \_____/\_| \_/\____/  \____/\_| |_/\_| \_/
                                                        
                                    ----by cwbird\n
 '''

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 110, 1101, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.jbxx = QtWidgets.QWidget()
        self.jbxx.setObjectName("jbxx")
        self.banner_out = QtWidgets.QTextBrowser(self.jbxx)
        self.banner_out.setGeometry(QtCore.QRect(0, 30, 1091, 341))
        self.banner_out.setObjectName("banner_out")
        self.tabWidget.addTab(self.jbxx, "")
        self.mlzx = QtWidgets.QWidget()
        self.mlzx.setObjectName("mlzx")
        self.cmd_out = QtWidgets.QTextBrowser(self.mlzx)
        self.cmd_out.setGeometry(QtCore.QRect(0, 61, 1111, 311))
        self.cmd_out.setObjectName("cmd_out")
        self.layoutWidget = QtWidgets.QWidget(self.mlzx)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mingling = QtWidgets.QLabel(self.layoutWidget)
        self.mingling.setObjectName("mingling")
        self.horizontalLayout_4.addWidget(self.mingling)
        self.commd_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.commd_input.setObjectName("commd_input")
        self.horizontalLayout_4.addWidget(self.commd_input)
        self.comm_perform = QtWidgets.QPushButton(self.layoutWidget)
        self.comm_perform.setObjectName("comm_perform")
        


        self.horizontalLayout_4.addWidget(self.comm_perform)
        self.tabWidget.addTab(self.mlzx, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.batch_Browser = QtWidgets.QTextBrowser(self.tab)
        self.batch_Browser.setGeometry(QtCore.QRect(0, 90, 1091, 271))
        self.batch_Browser.setObjectName("batch_Browser")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 19, 1071, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.file_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.file_input.setObjectName("file_input")
        self.horizontalLayout_2.addWidget(self.file_input)
        self.upload = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.upload.setObjectName("upload")
        self.horizontalLayout_2.addWidget(self.upload)
        self.piliang_scan = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.piliang_scan.setObjectName("piliang_scan")
        self.horizontalLayout_2.addWidget(self.piliang_scan)
        self.tabWidget.addTab(self.tab, "")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(580, 20, 521, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_2 = QtWidgets.QLabel(self.splitter_3)
        self.label_2.setObjectName("label_2")
        self.url_input = QtWidgets.QLineEdit(self.splitter_3)
        self.url_input.setObjectName("url_input")
        self.subm_button = QtWidgets.QPushButton(self.splitter_3)
        self.subm_button.setObjectName("subm_button")
        

        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 321, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.list_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.list_comboBox.setObjectName("list_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.list_comboBox)
        self.selec_label = QtWidgets.QLabel(self.layoutWidget1)
        self.selec_label.setObjectName("selec_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.selec_label)
        self.log_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_browser.setGeometry(QtCore.QRect(10, 520, 1091, 192))
        self.log_browser.setObjectName("log_browser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action1_gengxin = QtWidgets.QAction(MainWindow)
        self.action1_gengxin.setObjectName("action1_gengxin")
        self.action1_daochu = QtWidgets.QAction(MainWindow)
        self.action1_daochu.setObjectName("action1_daochu")
        self.action_tuichu = QtWidgets.QAction(MainWindow)
        self.action_tuichu.setObjectName("action_tuichu")
        self.menu.addSeparator()
        self.menu.addSeparator()
        self.menu.addAction(self.action1_daochu)
        self.menu.addAction(self.action_tuichu)
        self.menu_2.addSeparator()
        self.menu_2.addSeparator()
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action1)
        self.menu_2.addAction(self.action1_gengxin)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.action_tuichu.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Struts2漏洞扫描器 --by cwbird"))
        MainWindow.setStatusTip(_translate("MainWindow", "这是状态栏"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jbxx), _translate("MainWindow", "基本信息"))
        self.mingling.setText(_translate("MainWindow", "命令："))
        self.comm_perform.setText(_translate("MainWindow", "执行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mlzx), _translate("MainWindow", "命令执行"))
        self.label_3.setText(_translate("MainWindow", "文件路径"))
        self.upload.setText(_translate("MainWindow", "上传"))
        self.piliang_scan.setText(_translate("MainWindow", "开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "批量检查"))
        self.label_2.setText(_translate("MainWindow", "检查地址："))
        self.subm_button.setText(_translate("MainWindow", "检查漏洞"))

        self.selec_label.setText(_translate("MainWindow", "选择漏洞："))
        self.menu.setTitle(_translate("MainWindow", "选项"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.action1.setText(_translate("MainWindow", "关于"))
        self.action1.setIconText(_translate("MainWindow", "关于"))
        self.action1_gengxin.setText(_translate("MainWindow", "检查更新"))
        self.action1_daochu.setText(_translate("MainWindow", "导出批量检查结果"))
        self.action1_daochu.setStatusTip(_translate("MainWindow", "点击导出文件"))
        self.action_tuichu.setShortcut(_translate("MainWindow", "Ctrl+Q"))












        
